Repository Myra-Security-GmbH/terraform-provider-myrasec, pull requests merged in 2025-03, with the labels that each got.

#208 Waf documentation 2
  docs/data-sources/waf_actions.md
  docs/data-sources/waf_conditions.md
  docs/resources/tag_waf_rule.md
  docs/resources/waf_rule.md
  docs/variables.md
  myrasec/data_source_waf_actions.go
  myrasec/data_source_waf_rules.go
  myrasec/resource_myrasec_tag_waf_rule.go
  myrasec/resource_myrasec_waf_rule.go
Labels: documentation

#209 Update go version to maintained version
  .github/workflows/release.yml
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: dependencies, go

#207 Added support for DS record type;
  docs/data-sources/dns_records.md
  docs/resources/dns_record.md
  docs/variables.md
  go.mod
  go.sum
  myrasec/data_source_dns_records.go
  myrasec/resource_myrasec_dns_record.go
Labels: waiting
